service: nuxt-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  profile: 'your profile name' #ENV setup name

functions:
  nuxt:
    handler: handler.nuxt
    events:
      - http:
          path: /
          method: any
          cors: true

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
